version: "3.8"

services:
  # Service 1: The Database
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sentiment_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sentiment_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Service 2: Your FastAPI App
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      # Connection string to talk to the 'db' service
      - DATABASE_URL=postgresql://user:password@db:5432/sentiment_db
      # Pass your API key through to the container
      - FIN_NEWS_API_KEY=${FIN_NEWS_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # Sync code for live reloading (Development only)
      - .:/app

      # ... existing db and web services ...

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      # This tells Streamlit to talk to the 'web' container on port 8000
      - API_URL=http://web:8000
    depends_on:
      - web
    volumes:
      - ./frontend:/app

volumes:
  postgres_data:
