version: "3.8"

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sentiment_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sentiment_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: ./backend # <--- Pointing to new folder
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/sentiment_db
      - FIN_NEWS_API_KEY=${FIN_NEWS_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app # Sync code for dev

  frontend:
    build: ./frontend # <--- Pointing to new folder
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://web:8000
    depends_on:
      - web
    volumes:
      - ./frontend:/app

volumes:
  postgres_data:
